name: postgres
description: PostgreSQL database driver. Supports statement reuse and binary protocol.
version: 2.3.2
homepage: https://github.com/isoos/postgresql-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  buffer: ^1.1.0
  crypto: ^3.0.0
  collection: ^1.15.0
  sasl_scram:
    git:
      url: https://github.com/Oberhauser-Dev/sasl_scram_dart.git
      ref: main

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.3.0
  coverage: any
