name: postgres
description: PostgreSQL database driver. Supports statement reuse and binary protocol.
version: 2.3.0-null-safety.0
homepage: https://github.com/isoos/postgresql-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  buffer: ^1.0.6
  crypto: ^3.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.3.0
  coverage: any
